version: 2.1

orbs:
  docker: circleci/docker@1.0.1

workflows:
  commit:
    jobs:
      - build-and-push:
          context: docker-credentials

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - docker/install-docker-tools
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Images
          command: |
            docker-compose -f images/bot/docker-compose.yml build
            docker-compose -f images/bot-storage/docker-compose.yml build
      - run:
          name: Login on Docker Hub
          command: echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
      - run:
          name: Publish Docker Images
          command: |
            docker images
            docker-compose -f images/bot/docker-compose.yml push
            docker-compose -f images/bot-storage/docker-compose.yml push